version: '3'
services:
  baseline-app:
    build: qa/src/baseline
    ports:
      - "8081:8081"
    secrets:
      - git_token
    command: uvicorn baseline:app --host 0.0.0.0 --port 8081

  proxy-app:
    build: qa/src/proxy
    ports:
      - "8080:8080"
    secrets:
      - git_token
    command: uvicorn baseline:app --host 0.0.0.0 --port 8080

secrets:
  git_token:
    file: /home/artem/git_token.txt